### ISSUE TITLE
Number of coeffs too high?

### ISSUE THREAD

**Issue by gfreches** [da-h/sphericalHarmonicsFlow#1]
Hey, I'm using this package to approximate a function on a sphere of radius 100 and I keep getting a nRMSE of about 5% which is still pretty high for my purposes. For it to go down to about 1% I have to increase the model order to very high numbers which gives me way too many coefficients. Additionally, I don't understand how a model order of 5 can give 21 coefficients if by looking at the real harmonic expansion I should just expect 11 coefficients.

**Comment by da-h** [comment]
Hey *gfreches*,

thank you for your request. You are absolutely right! There was a mistake in the for-loop, that dismissed all Basis functions with m==0 except the first one.

**This should be fixed now.**

---

I also changed the arguments and the observables, so that it is more clear what results to expect.
For instance, consider the result of:
```
...
sh = SH(pts, center, channels, max_degree=5)
sh.basis_names
```
which outputs the names of all 36 basis functions of degree ≤5 (in the same order the coeffs appear):
```
['B(l=0,m=0)',
 'B(l=1,m=-1)',
 'B(l=1,m=0)',
 'B(l=1,m=1)',
 'B(l=2,m=-2)',
 'B(l=2,m=-1)',
 'B(l=2,m=0)',
 'B(l=2,m=1)',
 'B(l=2,m=2)',
 'B(l=3,m=-3)',
 'B(l=3,m=-2)',
 'B(l=3,m=-1)',
 'B(l=3,m=0)',
 'B(l=3,m=1)',
 'B(l=3,m=2)',
 'B(l=3,m=3)',
 'B(l=4,m=-4)',
 'B(l=4,m=-3)',
 'B(l=4,m=-2)',
 'B(l=4,m=-1)',
 'B(l=4,m=0)',
 'B(l=4,m=1)',
 'B(l=4,m=2)',
 'B(l=4,m=3)',
 'B(l=4,m=4)',
 'B(l=5,m=-5)',
 'B(l=5,m=-4)',
 'B(l=5,m=-3)',
 'B(l=5,m=-2)',
 'B(l=5,m=-1)',
 'B(l=5,m=0)',
 'B(l=5,m=1)',
 'B(l=5,m=2)',
 'B(l=5,m=3)',
 'B(l=5,m=4)',
 'B(l=5,m=5)']
```

Best regards,
*da-h*
